version: '3'
services:
  openvpn:
    build: ./docker/openvpn 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 7878:7878
      - 8989:8989
      - 9091:9091
      - 9117:9117
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ${OPENVPN_PROFILE_PATH}:/etc/openvpn/profile/
    environment:
      - OPENVPN_CONFIG=${OPENVPN_CONFIG_FILE}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - OPENVPN_OPTS=${OPENVPN_OPTS}
  transmission:
    image: linuxserver/transmission
    depends_on:
      - openvpn
    network_mode: "service:openvpn"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
    environment:
       - PUID=${USER_ID}
       - PGID=${GROUP_ID}
  jackett:
    image: linuxserver/jackett
    depends_on:
      - openvpn
    network_mode: "service:openvpn"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${JACKETT_CONFIG_PATH}:/config
      - ${JACKETT_DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - transmission
      - jackett
    network_mode: "service:openvpn"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG_PATH}:/config
      - ${SONARR_VIDEO_PATH}:/tv/
      - ${SONARR_DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
  radarr:
    image: linuxserver/radarr
    depends_on:
      - transmission
      - jackett
    network_mode: "service:openvpn"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG_PATH}:/config
      - ${RADARR_VIDEO_PATH}:/movies/
      - ${RADARR_DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}